### ISSUE TITLE
Missing items in dockerfile 

### ISSUE THREAD

**Issue by t-sanders** [yala/OncoServe_Public#2] opened 2019-07-11 15:54 UTC
- These requirements are missing:
RUN pip install -r OncoData_Public/requirements.txt
RUN pip install -r OncoNet_Public/requirements.txt

- torch is missing in requirements.txt

- Error when starting container:

 File "/OncoServe/wsgi.py", line 1, in <module>
    from scripts.app import app
  File "/OncoServe/scripts/app.py", line 12, in <module>
    import oncoserve.onconet_wrapper as onconet_wrapper
  File "/OncoServe/oncoserve/onconet_wrapper.py", line 9, in <module>
    import onconet.utils.parsing as parsing
ModuleNotFoundError: No module named 'onconet'

**Comment by Akhiladdh** [comment] 2019-07-15 03:33
@t-sanders were you able to pull the docker Imgae?
I am failing to pull the docker image with below error
**Error response from daemon: pull access denied for yala/oncoserve, repository does not exist or may require 'docker login'**

**Comment by lishen** [comment] 2019-07-15 14:17
> @t-sanders were you able to pull the docker Imgae?
> I am failing to pull the docker image with below error
> **Error response from daemon: pull access denied for yala/oncoserve, repository does not exist or may require 'docker login'**

I'm having the same problem. The docker image is no longer available. I wrote to the first author and didn't get any response.

**Comment by t-sanders** [comment] 2019-07-15 14:45
> @t-sanders were you able to pull the docker Imgae?
> I am failing to pull the docker image with below error
> **Error response from daemon: pull access denied for yala/oncoserve, repository does not exist or may require 'docker login'**

AFAIK the repo is not there. I understand that Adam is working on it.

**Comment by yala** [comment] 2019-07-16 19:48
Hey everyone,

I'm working on releasing the docker images. I'll follow up back on this chain ASAP. know that im on it and you can expect something in the next 2 or 3 days. 
In general, for access to the docker image, you should reach out to me directly with a note on your intended use-case, and i'll grant your dockerhub acct access.

**Comment by yala** [comment] 2019-07-25 23:22
closing, as is duplicate of other issue. Docker Image is now ready, so if you wish to be granted access, just reach out with a brief description of the study you intend to run. 

Thank you all for your patience

**Closed as completed by yala** 2019-07-25 23:22 UTC
